adminUser:
  password: local:k3s-alpine/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: craft.de.jet@gmail.com
  token: local:k3s-alpine/pipelineUser:token
  username: craft-de-jet
prow:
  hmacToken: local:k3s-alpine/prow:hmacToken
